# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Natesh Raj Ramalingam
title: Site Reliability Engineer
email: nateshraj7@gmail.com
website: https://natty-7.github.io/natesh-cv/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  natty-7
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: natesh-raj-ramalingam
# xing_username: jekyll
# pinterest_username: jekyll
youtube_username: '@BuildRunScale'
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/NateshPicture.jpg
about_content: | # this will include new lines to allow paragraphs
  Site Reliability Engineer seasoned in Azure, DevOps, Platform engineering and architecture, logging and monitoring of web applications.

  I am most skilled in: <mark>Azure</mark> , <mark>Linux</mark> and <mark>ELK</mark>

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: top-middle
  #       title: Super awesome project
  #       link: github.com/sproogen
  #       # link_text: Project Website
  #       additional_links:
  #         - title:  sproogen/modern-resume-theme
  #           icon: fab fa-github
  #           url: github.com/sproogen/modern-resume-theme
  #         # - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #         #   icon: fab fa-github
  #         #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: | # this will include new lines to allow paragraphs
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Insight
        link: www.insight.com
        # link_text: boringcompany.com
        sub_title: Site Reliability Engineer
        caption: December 2022 - Present
        quote: >
          Insight is a leading solutions integrator with services ranging from selling hardware, software to providing SME to clients.
        description: | # this will include new lines to allow paragraphs
            I work in the Platform and Reliability team managing insight.com web application. 
            Tech stack: Apache httpd, tomcat, SQL, mongo, RHEL 8, AEM, ELK stack, Akamai, Azure App gateway, Azure VMs, git, chef, jenkins, github actions.

      - layout: left
        title: Tata Consultancy Services
        link: www.tcs.com
        # link_text: boringcompany.com
        sub_title: Systems Engineer
        caption: November 2018 - December 2022
        quote: >
          Tata Consultancy Services helps businesses transform through technology. I worked for the client AutoNation.
        description: | # this will include new lines to allow paragraphs
            I worked in the DevOps team for the client Autonation (www.autonation.com)
            Tech stack: Azure DevOps, Octopus deploy, Azure Kubernetes Services, Azure app services, Azure Service bus, Azure Redis, Azure Automation, Azure Windows VM's, sitecore, c# .NET MVC, Azure Application Gateway, AppDynamics, Splunk, Dynatrace, Azure monitors, Azure application insights, Akamai

 
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Anna University
        caption: 2014 - 2018
        sub_title: Bachelor of Engineering (EEE)
        description: | # this will include new lines to allow paragraphs
          I studied Electrical and Electronics Engineer in Sri Sairam Engineering College under Anna university.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Systems and software engineering some of my other interests and hobbies are:
      - fitness
      - content creation

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
